=== By698/XML-studia/Zad2-XMLSchema/Wypożyczalnia.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="https://www.w3schools.com" 
  xmlns:bk="https://www.w3schools.com" 
  xmlns="https://www.w3schools.com" elementFormDefault="qualified">

  <xs:element name="movieRental">

    <xs:complexType>
      <xs:sequence>
        <xs:element ref="header"/>
        <xs:element ref="movies"/>
        <xs:element ref="borrows"/>
      </xs:sequence>
    </xs:complexType>

    <xs:unique name="unikalnyNrKlienta">
      <xs:selector xpath="./bk:borrows/bk:borrow/bk:client"/>
      <xs:field xpath="@id"/>
    </xs:unique>

    <xs:keyref name="bMovieID" refer="movieID">
      <xs:selector xpath="./bk:borrows/bk:borrow/bk:borrowedMovie"/>
      <xs:field xpath="@id"/>
    </xs:keyref>

    <xs:key name="movieID">
      <xs:selector xpath="./bk:movies/bk:movie"/>
      <xs:field xpath="@id"/>
    </xs:key>



  </xs:element>

  <!--Nagłówek-->
  <xs:element name="header">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="authors">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="author" type="xs:normalizedString" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="fileDescription" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!--Typy danych-->
  <xs:simpleType name="genreType">
    <xs:restriction base="xs:normalizedString">
      <xs:enumeration value="Dramat"/>
      <xs:enumeration value="Biograficzny"/>
      <xs:enumeration value="Dramat_sądowy"/>
      <xs:enumeration value="Fantasy"/>
      <xs:enumeration value="Gangsterski"/>
      <xs:enumeration value="Kryminał"/>
      <xs:enumeration value="Thriller"/>
      <xs:enumeration value="Surrealistyczny"/>
      <xs:enumeration value="Western"/>
      <xs:enumeration value="Animacja"/>
      <xs:enumeration value="Akcja"/>
      <xs:enumeration value="Dramat_historyczny"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="currencyType">
    <xs:restriction base="xs:token">
      <xs:pattern value="[A-Z]{3}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="firstNameType">
    <xs:restriction base="xs:normalizedString">
      <xs:maxLength value="10"/>
      <xs:minLength value="3"/>
      <xs:pattern value="[A-Z][a-z]*"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="lastNameType">
    <xs:restriction base="xs:normalizedString">
      <xs:maxLength value="20"/>
      <xs:minLength value="3"/>
      <xs:pattern value="[A-Z][a-z]+([- | \s][A-Z][a-z]+)?"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="ratingType">
    <xs:restriction base="xs:decimal">
      <xs:minInclusive value="0" />
      <xs:maxInclusive value="10" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="priceType">
    <xs:restriction base="xs:decimal">
      <xs:minInclusive value="0" />
      <xs:totalDigits value="4" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="idTypeClient">
    <xs:restriction base="xs:normalizedString">
      <xs:pattern value = "[c][0-9]{6}" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="idTypeMovie">
    <xs:restriction base="xs:normalizedString">
      <xs:pattern value = "[m][0-9]{4}" />
    </xs:restriction>
  </xs:simpleType>

  <!--Proste elementy w movies-->

  <xs:element name="title" type="xs:normalizedString"/>
  <xs:element name="director" type="xs:normalizedString"/>
  <xs:element name="year" type="xs:gYear"/>
  <xs:element name="rating" type="ratingType"/>
  <xs:element name="description" type="xs:string"/>
  <xs:element name="borrowsNumber" type="xs:nonNegativeInteger"/>

  <xs:group name="movieInfo">
    <xs:sequence>
      <xs:element ref="title" />
      <xs:element ref="director" />
      <xs:element ref="year" />
      <xs:element ref="rating" />
      <xs:element ref="description" />
    </xs:sequence>
  </xs:group>

  <!--Dodatkowe elementy w borrows-->
  <xs:element name="firstname" type="firstNameType"/>
  <xs:element name="lastname" type="lastNameType"/>
  <xs:element name="borrowDate" type="xs:date"/>
  <xs:element name="returnDate" type="xs:date"/>

  <!--Elementy złozone-->
  <xs:element name="price">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="priceType">
          <xs:attribute name="currency" type="currencyType"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="movie">
    <xs:complexType>
      <xs:sequence>
        <xs:group ref="movieInfo"/>
        <xs:element ref="price"/>
        <xs:element ref="borrowsNumber"/>
      </xs:sequence>
      <xs:attribute name="genre" type="genreType"/>
      <xs:attribute name="id" type="idTypeMovie" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="client">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="firstname"/>
        <xs:element ref="lastname"/>
      </xs:sequence>
      <xs:attribute name="id" type="idTypeClient" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="borrowedMovie">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="title"/>
        <xs:element ref="year"/>
      </xs:sequence>
      <xs:attribute name="id" type="idTypeMovie" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="borrow">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="client"/>
        <xs:element ref="borrowedMovie"/>
        <xs:element ref="borrowDate" />
        <xs:element ref="returnDate" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="borrows">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="borrow" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="movies">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="movie" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== By698/XML-studia/Zad2-XMLSchema/Wypożyczalnia.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="style.css" ?>

<movieRental xmlns="https://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://www.w3schools.com Wypożyczalnia.xsd">
  <header>
    <authors>
      <author>Damian Byszewski</author>
      <author>Bartosz Krukowski</author>
    </authors>
    <fileDescription>Wypożyczalnia filmów stworzona na potrzeby projektu z przedmiotu "Technologie XML".</fileDescription>
  </header>

  <movies>
    <movie genre="Dramat" id="m3273">
      <title>Więzień nienawiści</title>
      <director>Tony Kaye</director>
      <year>1998</year>
      <rating>8.14</rating>
      <description>Były neonazista po wyjściu z więzienia stara się przekonać młodszego brata, by nie podążał jego śladem.</description>
      <price currency="PLN">16.99</price>
      <borrowsNumber>1</borrowsNumber>
    </movie>
    <movie genre="Akcja" id="m7256">
      <title>Avengers: Wojna bez granic</title>
      <director>Anthony Russo</director>
      <year>2018</year>
      <rating>8.12</rating>
      <description>Potężny Thanos zbiera Kamienie Nieskończoności w celu narzucenia swojej woli wszystkim istnieniom we wszechświecie. Tylko drużyna superbohaterów znanych jako Avengers może go powstrzymać.</description>
      <price currency="PLN">5.99</price>
      <borrowsNumber>2</borrowsNumber>
    </movie>
    <movie genre="Western" id="m5829">
      <title>Django</title>
      <director>Quentin Tarantino</director>
      <year>2012</year>
      <rating>8.21</rating>
      <description>Łowca nagród Schultz i czarnoskóry niewolnik Django wyruszają w podróż, aby odbić żonę tego drugiego z rąk bezlitosnego Calvina Candie'ego.</description>
      <price currency="PLN">14.99</price>
      <borrowsNumber>1</borrowsNumber>
    </movie>
    <movie genre="Dramat" id="m9328">
      <title>Człowiek z blizną</title>
      <director>Brian De Palma</director>
      <year>1983</year>
      <rating>8.2</rating>
      <description>Kubański emigrant Tony Montana opuszcza ojczyznę i przybywa do Miami. Razem z przyjacielem, Mannym Riberą, zaczyna pracować dla mafii narkotykowej.</description>
      <price currency="PLN">11.99</price>
      <borrowsNumber>1</borrowsNumber>
    </movie>
    <movie genre="Biograficzny" id="m5620">
      <title>Nietykalni</title>
      <director>Olivier Nakache</director>
      <year>2011</year>
      <rating>8.64</rating>
      <description>Sparaliżowany milioner zatrudnia do opieki młodego chłopaka z przedmieścia, który właśnie wyszedł z więzienia.</description>
      <price currency="PLN">16.99</price>
      <borrowsNumber>1</borrowsNumber>
    </movie>
    <movie genre="Dramat_sądowy" id="m1161">
      <title>Dwunastu gniewnych ludzi</title>
      <director>Sidney Lumet</director>
      <year>1957</year>
      <rating>8.53</rating>
      <description>Dwunastu przysięgłych ma wydać wyrok w procesie o morderstwo. Jeden z nich ma wątpliwości dotyczące winy oskarżonego.</description>
      <price currency="PLN">12.99</price>
      <borrowsNumber>1</borrowsNumber>
    </movie>
    <movie genre="Kryminał" id="m4739">
      <title>Siedem</title>
      <director>David Fincher</director>
      <year>1995</year>
      <rating>8.27</rating>
      <description>Dwóch policjantów stara się złapać seryjnego mordercę wybierającego swoje ofiary wg specjalnego "klucza".</description>
      <price currency="PLN">15.99</price>
      <borrowsNumber>1</borrowsNumber>
    </movie>
    <movie genre="Dramat" id="m7034">
      <title>Chłopiec w pasiastej piżamie</title>
      <director>Mark Herman</director>
      <year>2008</year>
      <rating>8.09</rating>
      <description>Ośmioletni syn niemieckiego oficera SS zaprzyjaźnia się z żydowskim chłopcem przebywającym w obozie.</description>
      <price currency="PLN">5.99</price>
      <borrowsNumber>1</borrowsNumber>
    </movie>
    <movie genre="Dramat" id="m1786">
      <title>Zielona mila</title>
      <director>Frank Darabont</director>
      <year>1999</year>
      <rating>8.61</rating>
      <description>Emerytowany strażnik więzienny opowiada przyjaciółce o niezwykłym mężczyźnie, którego skazano na śmierć za zabójstwo dwóch 9-letnich dziewczynek.</description>
      <price currency="PLN">5.99</price>
      <borrowsNumber>1</borrowsNumber>
    </movie>
    <movie genre="Dramat_historyczny" id="m3573">
      <title>Gladiator</title>
      <director>Ridley Scott</director>
      <year>2000</year>
      <rating>8.08</rating>
      <description>Generał Maximus - prawa ręka cesarza, szczęśliwy mąż i ojciec - w jednej chwili traci wszystko. Jako niewolnik-gladiator musi walczyć na arenie o przeżycie.</description>
      <price currency="PLN">18.99</price>
      <borrowsNumber>3</borrowsNumber>
    </movie>
    <movie genre="Dramat" id="m4253">
      <title>Lot nad kukułczym gniazdem</title>
      <director>Miloš Forman</director>
      <year>1975</year>
      <rating>8.45</rating>
      <description>Historia złodzieja, szulera i chuligana, który, by uniknąć więzienia, udaje niepoczytalność. Trafia do szpitala dla umysłowo chorych, gdzie twardą ręką rządzi siostra Ratched.</description>
      <price currency="PLN">7.99</price>
      <borrowsNumber>3</borrowsNumber>
    </movie>
    <movie genre="Thriller" id="m7542">
      <title>Podziemny krąg</title>
      <director>David Fincher</director>
      <year>1999</year>
      <rating>8.26</rating>
      <description>Dwóch mężczyzn znudzonych rutyną zakłada klub, w którym co tydzień odbywają się walki na gołe pięści.</description>
      <price currency="PLN">18.99</price>
      <borrowsNumber>2</borrowsNumber>
    </movie>
    <movie genre="Animacja" id="m1834">
      <title>Król Lew</title>
      <director>Rob Minkoff</director>
      <year>1994</year>
      <rating>8.2</rating>
      <description>Targany niesłusznymi wyrzutami sumienia po śmierci ojca mały lew Simba skazuje się na wygnanie, rezygnując z przynależnego mu miejsca na czele stada.</description>
      <price currency="PLN">4.99</price>
      <borrowsNumber>2</borrowsNumber>
    </movie>
    <movie genre="Dramat" id="m6550">
      <title>Forrest Gump</title>
      <director>Robert Zemeckis</director>
      <year>1994</year>
      <rating>8.52</rating>
      <description>Historia życia Forresta, chłopca o niskim ilorazie inteligencji z niedowładem kończyn, który staje się miliarderem i bohaterem wojny w Wietnamie.</description>
      <price currency="PLN">18.99</price>
      <borrowsNumber>2</borrowsNumber>
    </movie>
    <movie genre="Dramat" id="m4890">
      <title>Wyspa tajemnic</title>
      <director>Martin Scorsese</director>
      <year>2010</year>
      <rating>8.15</rating>
      <description>Szeryf federalny Daniels stara się dowiedzieć, jakim sposobem z zamkniętej celi w pilnie strzeżonym szpitalu dla chorych psychicznie przestępców zniknęła pacjentka.</description>
      <price currency="PLN">18.99</price>
      <borrowsNumber>1</borrowsNumber>
    </movie>
    <movie genre="Thriller" id="m1774">
      <title>Milczenie owiec</title>
      <director>Jonathan Demme</director>
      <year>1991</year>
      <rating>8.21</rating>
      <description>Seryjny morderca i inteligentna agentka łączą siły, by znaleźć przestępcę obdzierającego ze skóry swoje ofiary.</description>
      <price currency="PLN">17.99</price>
      <borrowsNumber>1</borrowsNumber>
    </movie>
    <movie genre="Gangsterski" id="m4372">
      <title>Pulp Fiction</title>
      <director>Quentin Tarantino</director>
      <year>1994</year>
      <rating>8.32</rating>
      <description>Przemoc i odkupienie w opowieści o dwóch płatnych mordercach pracujących na zlecenie mafii, żonie gangstera, bokserze i parze okradającej ludzi w restauracji.</description>
      <price currency="PLN">9.99</price>
      <borrowsNumber>2</borrowsNumber>
    </movie>
    <movie genre="Dramat" id="m2760">
      <title>Chłopcy z ferajny</title>
      <director>Martin Scorsese</director>
      <year>1990</year>
      <rating>8.24</rating>
      <description>Kilkunastoletni Henry i Tommy DeVito trafiają pod opiekę potężnego gangstera. Obaj szybko uczą się panujących w mafii reguł.</description>
      <price currency="PLN">17.99</price>
      <borrowsNumber>2</borrowsNumber>
    </movie>
    <movie genre="Dramat" id="m7968">
      <title>Lista Schindlera</title>
      <director>Steven Spielberg</director>
      <year>1993</year>
      <rating>8.33</rating>
      <description>Historia przedsiębiorcy Oskara Schindlera, który podczas II wojny światowej uratował przed pobytem w obozach koncentracyjnych 1100 Żydów.</description>
      <price currency="PLN">9.99</price>
      <borrowsNumber>1</borrowsNumber>
    </movie>
    <movie genre="Surrealistyczny" id="m4030">
      <title>Incepcja</title>
      <director>Christopher Nolan</director>
      <year>2010</year>
      <rating>8.23</rating>
      <description>Czasy, gdy technologia pozwala na wchodzenie w świat snów. Złodziej Cobb ma za zadanie wszczepić myśl do śpiącego umysłu.</description>
      <price currency="PLN">6.99</price>
      <borrowsNumber>3</borrowsNumber>
    </movie>
    <movie genre="Dramat" id="m8073">
      <title>Życie jest piękne</title>
      <director>Roberto Benigni</director>
      <year>1997</year>
      <rating>8.29</rating>
      <description>Zamknięty w obozie koncentracyjnym wraz z synem Guido próbuje przekonać chłopca, że okrutna rzeczywistość jest jedynie formą zabawy dla dorosłych.</description>
      <price currency="PLN">8.99</price>
      <borrowsNumber>2</borrowsNumber>
    </movie>
    <movie genre="Biograficzny" id="m9054">
      <title>Piękny umysł</title>
      <director>Ron Howard</director>
      <year>2001</year>
      <rating>8.24</rating>
